spring:
  datasource:
    url: jdbc:mysql://localhost:3306/peini?useSSL=false&useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      test-while-idle: true
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
      max-idle: 20
      min-idle: 5
    platform: mysql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
logging:
  level:
    org:
      hibernate:
        SQL: debug

